workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - flutter pub get
      - flutter clean
      - cd ios
      - rm -rf Pods Podfile.lock
      - pod repo update
      - cd ..
      - flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa